export const auth_base_url = "http://localhost:8000/auth"
export const customers_base_url = "http://localhost:8000"
export const products_base_url = "http://localhost:8000/product"
export const brands_base_url = "http://localhost:8000/brand"
export const product_category_base_url = "http://localhost:8000/product-category"
export const blog_category_base_url = "http://localhost:8000/blog-category"