export const auth_base_url = "http://localhost:8000"
export const customers_base_url = "http://localhost:8000"
export const products_base_url = "http://localhost:8000/product"
export const brands_base_url = "http://localhost:8000/brand"
export const product_category_base_url = "http://localhost:8000/product-category"
export const blog_category_base_url = "http://localhost:8000/blog-category"
export const color_base_url = "http://localhost:8000/color"
export const enquiry_base_url = "http://localhost:8000/enquiry"
export const coupons_base_url = "http://localhost:8000/coupon"
export const orders_base_url = "http://localhost:8000/order"

// export const auth_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com"
// export const customers_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com"
// export const products_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/product"
// export const brands_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/brand"
// export const product_category_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/product-category"
// export const blog_category_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/blog-category"
// export const color_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/color"
// export const enquiry_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/enquiry"
// export const coupons_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/coupon"
// export const orders_base_url = "https://ecommerce-mern-shopkart-backend.onrender.com/order"


/* testing */
// export const auth_base_url = "http://192.168.43.196:8000"
// export const customers_base_url = "http://192.168.43.196:8000"
// export const products_base_url = "http://192.168.43.196:8000/product"
// export const brands_base_url = "http://192.168.43.196:8000/brand"
// export const product_category_base_url = "http://192.168.43.196:8000/product-category"
// export const blog_category_base_url = "http://192.168.43.196:8000/blog-category"
// export const color_base_url = "http://192.168.43.196:8000/color"
// export const enquiry_base_url = "http://192.168.43.196:8000/enquiry"
// export const orders_base_url = "http://192.168.43.196:8000/order"
// export const coupons_base_url = "http://192.168.43.196:8000/coupon"